/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qZKGYBzT69r
 */
import Link from "next/link"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="bg-white text-gray-900">
      <header className="flex justify-between items-center p-4 border-b">
        <div>
          <img alt="Panaverse DAO" className="h-8" src="/placeholder.svg" />
        </div>
        <nav className="flex space-x-4">
          <Link className="text-blue-600 hover:text-blue-800" href="#">
            Home
          </Link>
          <Select>
            <SelectTrigger id="course">
              <SelectValue placeholder="course" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="course1">Course 1</SelectItem>
              <SelectItem value="course2">Course 2</SelectItem>
            </SelectContent>
          </Select>
        </nav>
      </header>
      <main className="px-4 py-8">
        <section className="mb-12">
          <h1 className="text-3xl font-bold mb-4">Certified Web 3.0 and Metaverse Developer</h1>
          <p className="mb-4">
            A One and Quarter Years Panaverse DAO Earn as you Learn Program Getting Ready for the Next Generation of the
            Internet
          </p>
          <p className="mb-4">
            Consolidating Web 3.0, Metaverse, Artificial Intelligence (AI), Cloud, Edge, Ambient Computing/IoT, Network
            Automation, and Bioinformatics Technologies
          </p>
          <Button className="bg-blue-600 text-white">Learn More</Button>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">Program of Studies</h2>
          <h3 className="text-xl font-semibold mb-2">Core Courses (Common in All Specializations)</h3>
          <p className="mb-4">
            Every participant of the program will start by completing the following three core courses.
          </p>
          <Button className="bg-blue-600 text-white mb-4">Enroll Now</Button>
          <div className="flex items-center space-x-8 mb-4">
            <div className="flex flex-col items-center">
              <p className="font-bold">Quarter I</p>
              <p>CS-101: Object-Oriented Programming using TypeScript</p>
            </div>
            <div className="flex flex-col items-center">
              <p className="font-bold">Quarter II</p>
              <p>
                W2-201: Developing Planet-Scale Web 2.0 Serverless Cloud Cloud Apps and APIs using Next.js 13 and Cloud
                Development Kit (CDK) for Terraform
              </p>
            </div>
            <div className="flex flex-col items-center">
              <p className="font-bold">Quarter III</p>
              <p>S-101: Dollar Making Bootcamp - Full-Stack Template and API Product Development</p>
            </div>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">Specialized Tracks:</h2>
          <p className="mb-4">
            After completing the first three quarters the participants will select one or more specializations
            consisting of two courses each.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4" />
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">The Outcome for Participants of the Program</h2>
          <p className="mb-4">
            As a graduate of this program, you will own valuable products such as Full-Stack App Templates, AR and VR
            Experiences, and APIs that are marketed globally by the Panaverse DAO. You will also have the opportunity to
            offer your services at a rate of $50 per hour, providing a path to financial stability while contributing to
            the growth of Pakistan's software exports.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4" />
        </section>
        <footer className="border-t p-4">
          <div className="flex justify-between items-center">
            <div>
              <img alt="Panaverse DAO" className="h-8" src="/placeholder.svg" />
              <p>
                Web 3.0 and Metaverse Developer A One and Quarter Years Panaverse DAO Earn as you Learn Program Getting
                Ready for the Next Generation of the Internet
              </p>
            </div>
            <div className="flex space-x-2">
              <FacebookIcon className="text-blue-600" />
              <YoutubeIcon className="text-red-600" />
              <TwitterIcon className="text-blue-400" />
              <SmartphoneIcon className="text-green-500" />
            </div>
          </div>
          <div className="flex justify-between items-center mt-4">
            <div className="flex flex-col space-y-2">
              <h3 className="font-bold">Programs</h3>
              <p>Web 3.0 and Metaverse Developer</p>
              <p>Artificial Intelligence</p>
              <p>Cloud-Native Computing</p>
              <p>Ambient Computing and IoT</p>
              <p>Genomics and Bioinformatics</p>
              <p>Network Programmability and Automation</p>
            </div>
            <div className="flex flex-col space-y-2">
              <h3 className="font-bold">Pages</h3>
              <Link className="text-blue-600 hover:text-blue-800" href="#">
                Home
              </Link>
              <Link className="text-blue-600 hover:text-blue-800" href="#">
                Quarter 1
              </Link>
              <Link className="text-blue-600 hover:text-blue-800" href="#">
                Quarter 2
              </Link>
              <Link className="text-blue-600 hover:text-blue-800" href="#">
                Quarter 3
              </Link>
            </div>
          </div>
        </footer>
      </main>
    </div>
  )
}


function FacebookIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function YoutubeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}


function TwitterIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function SmartphoneIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}
